root_dir: ./data

data:
  download:
    subdir: raw
    url: https://www.dropbox.com/s/dsltirre6hu724g/train.zip
    zip_file: train.zip
  download_val:
    subdir: raw
    url: https://www.dropbox.com/s/tuyavsee0i6oqhy/test.zip
    zip_file: test.zip
  dataset:
    subdir: dataset

train:
  subdir: train

