name: train-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
  
    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: iterative/setup-dvc@v1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          
          # Pull dataset with DVC 
          dvc pull data
          
          # Reproduce pipeline if any changes detected in dependencies
          dvc repro 
          
          # Use DVC metrics diff to compare metrics to master
          git fetch --prune --unshallow
          dvc metrics diff --show-md master >> report.md
